server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  file: eureka.log
  level: INFO

info.app.name: '@project.name@'
info.app.version: '@project.version@'

