info.app.name: '@project.name@'
info.app.version: '@project.version@'

logging:
  file: data-presentation.log
  level:
    com:
      netflix: DEBUG

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    appname: '@project.name@'
    prefer-ip-address: true
    preferIpAddress: true