info.app.name: '@project.name@'
info.app.version: '@project.version@'

server:
  port: 8084

logging:
   config:
      classpath: "logback-spring.xml"
   file: data-presentation.log

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
  instance:
    appname: '@project.name@'
    preferIpAddress: true
